### PR TITLE
Feature/add mongo db

### PR DESCRIPTION
**Pull request by stufinn**
Adds a basic implementation of database functionality to the contact form and reservation requests. The website should work as usual with the 'node server.js' command, but database functionality will only work properly if you have mongoDB installed and running locally or if you visit the live site at https://schrutefarmsbnb.herokuapp.com/.  I am using Robo3T to view the local database and Postman to manually test the POST requests.

### CODE REVIEW

**Comment by Jaffacake85** [comment]
Looks Good!

**Comment by Jaffacake85** [comment]
Sorry for closing... I was just adding a comment

**Comment by stufinn** [comment]
Haha No prob and thanks @Jaffacake85 . Can you pls approve the PR below? Once approved feel free to merge it too!

**Comment by Jaffacake85** [comment]
It won't let me merge this from my phone so I'll merge as soon as I get out of this meeting

**Pull request merged**
